services:
  immo_apigateway:
    restart: no
    build: .
    ports:
      - 4000:4000
    volumes:
      - .m2:/root/.m2
    networks:
      - immo-network

networks:
  immo-network:
    external: true