spring:
  application:
    name: immo-api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://IMMO-AUTHENTIFICATION-SERVER
          predicates:
            - Path=/api/auth/**, /api/account/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
            allowedHeaders:
              - Content-Type
              - responseType
              - Authorization
            allowCredentials: true
server:
  port: 4000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://immo-eureka-server:8761/eureka
  instance:
    hostname: immo-api-gateway

gateway:
  excludedUrl: /api/auth/register, /api/auth/login

keyStore:
  path: keystore.jks
  password: password
  alias: auth-server